# Generated by Django 5.2 on 2026-09-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=128, verbose_name='作者')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='分类')),
                ('file_path', models.CharField(blank=True, max_length=512, verbose_name='文件/路径')),
                ('cover', models.CharField(blank=True, max_length=512, verbose_name='封面')),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('progress', models.IntegerField(default=0, verbose_name='当前进度(页)')),
                ('status', models.CharField(choices=[('unread', '未读'), ('reading', '在读'), ('done', '读完')], default='unread', max_length=16, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GoldenSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='金句')),
                ('source', models.CharField(blank=True, max_length=256, verbose_name='出处')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': '金句',
                'verbose_name_plural': '金句',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=64, verbose_name='位置')),
                ('note', models.TextField(blank=True, verbose_name='笔记')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bookshelf.book', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '读书笔记',
                'verbose_name_plural': '读书笔记',
                'ordering': ['-created'],
            },
        ),
    ]
