# Generated by Django 5.2 on 2026-09-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='来源链接'),
        ),
    ]
