# Generated by Django 5.2 on 2026-09-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='来源链接'),
        ),
    ]
