# Generated by Django 5.2.18 on 2026-10-08 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_goldensentence_book_node'),
        ('core', '0013_asset_deletednode_job_nodeproposal_noderevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset'),
        ),
    ]
