# Generated by Django 5.2 on 2026-09-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('kind', models.CharField(choices=[('build', '平台搭建库'), ('runtime', '运行库')], default='runtime', max_length=16, verbose_name='类型')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='系统', max_length=64, verbose_name='操作者')),
                ('module', models.CharField(max_length=32, verbose_name='模块')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('detail', models.TextField(blank=True, verbose_name='明细')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='键')),
                ('value', models.TextField(blank=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('local', '本地导入'), ('web', '网页解析'), ('video', '视频转图文'), ('text', '文本输入')], max_length=16, verbose_name='类型')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='标题')),
                ('raw_text', models.TextField(blank=True, verbose_name='原始内容')),
                ('parsed_md', models.TextField(blank=True, verbose_name='解析结果(Markdown)')),
                ('source_url', models.CharField(blank=True, max_length=1024, verbose_name='来源链接')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.knowledgebase', verbose_name='归入库')),
            ],
            options={
                'verbose_name': '收集项',
                'verbose_name_plural': '收集项',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content_md', models.TextField(blank=True, verbose_name='正文(Markdown)')),
                ('node_type', models.CharField(choices=[('wiki', 'WiKI 页'), ('article', '文章'), ('doc', '资料'), ('note', '笔记')], default='wiki', max_length=16, verbose_name='类型')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='分类')),
                ('tags', models.CharField(blank=True, help_text='逗号分隔', max_length=256, verbose_name='标签')),
                ('source', models.CharField(blank=True, max_length=256, verbose_name='来源')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.knowledgebase', verbose_name='所属库')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.knowledgenode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '知识节点',
                'verbose_name_plural': '知识节点',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=64, verbose_name='关系')),
                ('kind', models.CharField(choices=[('link', '链接'), ('backlink', '反向链接'), ('related', '相关')], default='related', max_length=16, verbose_name='类型')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='core.knowledgenode', verbose_name='源')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='core.knowledgenode', verbose_name='目标')),
            ],
            options={
                'verbose_name': '关系',
                'verbose_name_plural': '关系',
            },
        ),
    ]
