# Generated by Django 5.2 on 2026-09-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='directory',
            field=models.CharField(blank=True, help_text='如：03_知识库/08_WIKI，留空则使用默认目录', max_length=256, verbose_name='映射目录（相对 C:\\ZSK\\ZhiShi）'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='kind',
            field=models.CharField(choices=[('build', '平台搭建库'), ('runtime', '运行档案库'), ('knowledge', '知识库')], default='knowledge', max_length=16, verbose_name='类型'),
        ),
    ]
