# Generated by Django 5.2 on 2026-09-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_knowledgebase_directory_alter_knowledgebase_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='show_in_kb',
            field=models.BooleanField(default=True, verbose_name='在知识库展示'),
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024, unique=True, verbose_name='链接')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='标题')),
                ('source', models.CharField(choices=[('web', '网页解析'), ('selection', '划词收藏'), ('bookmark', '书签导入'), ('import', '批量导入'), ('manual', '手动添加')], default='manual', max_length=16, verbose_name='来源')),
                ('link_type', models.CharField(choices=[('webpage', '网页'), ('video', '视频'), ('paper', '论文'), ('pdf', 'PDF'), ('forum', '论坛'), ('social', '社交动态'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='类型')),
                ('unparse_reason', models.CharField(choices=[('paywall', '付费墙'), ('js_render', 'JS动态渲染'), ('antibot', '反爬阻断'), ('unsupported', '格式不支持'), ('timeout', '超时'), ('login_wall', '登录墙'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='无法解析原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('archived', '已归档'), ('invalid', '已作废')], default='pending', max_length=16, verbose_name='状态')),
                ('tags', models.CharField(blank=True, help_text='逗号分隔，如：待读,高优', max_length=256, verbose_name='标签')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('collector', models.CharField(default='系统', max_length=64, verbose_name='采集者')),
                ('domain', models.CharField(blank=True, max_length=128, verbose_name='域名')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='最近重试')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('related_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.knowledgebase', verbose_name='关联知识库')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接库',
                'ordering': ['-collected_at'],
            },
        ),
    ]
