# Generated by Django 5.2 on 2026-09-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_set_kb_display_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=64, verbose_name='位置')),
                ('note', models.TextField(blank=True, verbose_name='笔记')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.knowledgenode', verbose_name='知识节点')),
            ],
            options={
                'verbose_name': '节点笔记',
                'verbose_name_plural': '节点笔记',
                'ordering': ['-created'],
            },
        ),
    ]
