# Generated by Django 5.2 on 2026-09-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nodenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('local', '本地导入'), ('web', '网页解析'), ('video', '视频转图文'), ('text', '文本输入'), ('image', '图片上传')], max_length=16, verbose_name='类型'),
        ),
    ]
