# Generated by Django 5.2 on 2026-09-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_collectionitem_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='kind',
            field=models.CharField(choices=[('runtime', '运行档案库'), ('knowledge', '知识库')], default='knowledge', max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='linkitem',
            name='link_type',
            field=models.CharField(choices=[('webpage', '网页'), ('wechat', '公众号文章'), ('bilibili', 'B站视频'), ('video', '视频'), ('paper', '论文'), ('pdf', 'PDF'), ('forum', '论坛'), ('social', '社交动态'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='linkitem',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('archived', '链接归档'), ('invalid', '已作废')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
