# Generated by Django 5.2 on 2026-09-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_knowledgebase_kind_alter_linkitem_link_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('original_path', models.TextField(verbose_name='原始文件路径')),
                ('category', models.CharField(default='未分类', help_text='来自工作文件夹的子目录，或「上传文件」', max_length=128, verbose_name='分类')),
                ('source', models.CharField(choices=[('folder', '工作文件夹'), ('upload', '上传文件')], default='folder', max_length=16, verbose_name='来源')),
                ('ext', models.CharField(blank=True, max_length=16, verbose_name='扩展名')),
                ('size', models.BigIntegerField(default=0, verbose_name='大小(字节)')),
                ('mtime', models.FloatField(default=0, verbose_name='修改时间')),
                ('extracted', models.TextField(blank=True, help_text='解析出的纯文本 / Markdown，用于检索与概要展示', verbose_name='提取内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作文件索引',
                'verbose_name_plural': '工作文件索引',
                'ordering': ['category', 'title'],
            },
        ),
    ]
