# Generated by Django 5.2 on 2026-09-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workfileindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='note',
            field=models.TextField(blank=True, verbose_name='结果说明'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('local', '本地导入'), ('web', '网页解析'), ('video', '视频转图文'), ('text', '文本输入'), ('image', '图片上传'), ('office', '存入办公平台')], max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='status',
            field=models.CharField(choices=[('pending', '进行中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
