# Generated by Django 5.2 on 2026-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_collectionitem_note_alter_collectionitem_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenode',
            name='ai_generated',
            field=models.BooleanField(default=False, verbose_name='AI 生成'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='origin_ref',
            field=models.CharField(blank=True, help_text='原始文档标识：节点 pk 或 office 记录 pk；multi 时存 JSON 列表', max_length=1024, verbose_name='来源引用'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='origin_title',
            field=models.CharField(blank=True, max_length=256, verbose_name='来源标题'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='origin_type',
            field=models.CharField(blank=True, help_text='kb_node / office_advise / office_report / office_workfile / multi', max_length=24, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('adopted', '已采纳')], default='adopted', help_text='待处理=AI 提炼草稿，采纳后进入正式知识层', max_length=16, verbose_name='沉淀状态'),
        ),
    ]
