# Generated by Django 5.2 on 2026-09-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_knowledgenode_ai_generated_knowledgenode_origin_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgenode',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('adopted', '已采纳')], default='adopted', help_text='pending=AI 提炼草稿；adopted=已采纳进入正式知识层', max_length=16, verbose_name='沉淀状态'),
        ),
    ]
