# Generated by Django 5.2 on 2026-09-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_knowledgenode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkitem',
            name='unparse_reason',
            field=models.CharField(choices=[('paywall', '付费墙'), ('js_render', 'JS动态渲染'), ('antibot', '反爬阻断'), ('unsupported', '格式不支持'), ('timeout', '超时'), ('login_wall', '登录墙'), ('invalid', '链接失效'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='无法解析原因'),
        ),
    ]
