# Generated by Django 5.2.18 on 2026-10-08 03:22

import django.db.models.deletion
from django.db import migrations, models


def preserve_duplicate_edges(apps, schema_editor):
    Edge = apps.get_model('core', 'Edge')
    Archive = apps.get_model('core', 'DeletedNode')
    alias = schema_editor.connection.alias
    duplicates = Edge.objects.using(alias).values('source_id', 'target_id', 'kind').annotate(n=models.Count('id')).filter(n__gt=1)
    for group in duplicates.iterator():
        matches = Edge.objects.using(alias).filter(source_id=group['source_id'], target_id=group['target_id'], kind=group['kind']).order_by('pk')
        records = [{**row, 'created': row['created'].isoformat()} for row in matches.values()]
        Archive.objects.using(alias).create(original_id=-records[0]['id'],
            snapshot={'type': 'duplicate_edges', 'records': records})
        matches.exclude(pk=records[0]['id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_linkitem_unparse_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=256)),
                ('storage_path', models.CharField(max_length=512, unique=True)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.BigIntegerField()),
                ('snapshot', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('active_key', models.CharField(max_length=256, null=True, unique=True)),
                ('owner', models.CharField(blank=True, max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_until', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_version', models.PositiveIntegerField()),
                ('proposed', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_version', models.CharField(max_length=64)),
                ('content_md', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='original_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.collectionitem'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='export_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='export_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='export_status',
            field=models.CharField(default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(preserve_duplicate_edges, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'kind'), name='unique_edge'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset'),
        ),
        migrations.AddField(
            model_name='nodeproposal',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.knowledgenode'),
        ),
        migrations.AddField(
            model_name='noderevision',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.knowledgenode'),
        ),
        migrations.AddField(
            model_name='parseddocument',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset'),
        ),
        migrations.AddConstraint(
            model_name='noderevision',
            constraint=models.UniqueConstraint(fields=('node', 'version'), name='unique_node_revision'),
        ),
        migrations.AddConstraint(
            model_name='parseddocument',
            constraint=models.UniqueConstraint(fields=('asset', 'parser_version'), name='unique_parsed_asset'),
        ),
    ]
