# Generated by Django 5.2 on 2026-09-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('monthly', '月报'), ('yearly', '年报')], max_length=16, verbose_name='类型')),
                ('content_md', models.TextField(blank=True, verbose_name='内容(Markdown)')),
                ('range_start', models.DateField(blank=True, null=True, verbose_name='起始')),
                ('range_end', models.DateField(blank=True, null=True, verbose_name='结束')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('admin', '行政管理'), ('party', '基层党建'), ('ops', '网络运维')], default='admin', max_length=16, verbose_name='类别')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '工作记录',
                'verbose_name_plural': '工作记录',
                'ordering': ['-date'],
            },
        ),
    ]
