# Generated by Django 5.2 on 2026-09-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='category',
            field=models.CharField(choices=[('admin', '行政管理'), ('party', '基层党建'), ('ops', '网络运维'), ('archive', '工作记录')], default='admin', max_length=16, verbose_name='类别'),
        ),
    ]
