# Generated by Django 5.2 on 2026-09-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_workrecord_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('admin', '行政管理'), ('party', '基层党建'), ('ops', '网络运维'), ('archive', '工作记录')], default='admin', max_length=16, verbose_name='工作类别')),
                ('topic', models.CharField(max_length=200, verbose_name='主题')),
                ('content_md', models.TextField(blank=True, verbose_name='献策内容(Markdown)')),
                ('source', models.CharField(choices=[('ai', 'AI 生成'), ('local', '本地汇总')], default='ai', max_length=16, verbose_name='生成方式')),
                ('file_path', models.TextField(blank=True, verbose_name='输出文件路径')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': 'AI 献策',
                'verbose_name_plural': 'AI 献策',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='file_path',
            field=models.TextField(blank=True, verbose_name='输出文件路径'),
        ),
    ]
