# Generated by Django 5.2.18 on 2026-10-08 03:22

from django.db import migrations, models


def mark_legacy_archive(apps, schema_editor):
    WorkRecord = apps.get_model('office', 'WorkRecord')
    # Lost legacy categories cannot be inferred; keep 'archive' as a visible review marker.
    WorkRecord.objects.using(schema_editor.connection.alias).filter(category='archive').update(is_archived=True)


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_advise_report_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(mark_legacy_archive, migrations.RunPython.noop),
    ]
