# Generated by Django 5.2 on 2026-09-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('knowledge', '知识备份'), ('system', '系统备份'), ('migration', '迁移备份')], max_length=16, verbose_name='备份类型')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '进行中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('stage', models.CharField(blank=True, max_length=80, verbose_name='当前阶段')),
                ('message', models.TextField(blank=True, verbose_name='结果说明')),
                ('package_path', models.TextField(blank=True, verbose_name='备份包路径')),
                ('package_name', models.CharField(blank=True, max_length=200, verbose_name='包名')),
                ('package_size', models.BigIntegerField(default=0, verbose_name='包体积(字节)')),
                ('file_count', models.IntegerField(default=0, verbose_name='文件数')),
                ('options_json', models.TextField(blank=True, verbose_name='选项')),
                ('scope_json', models.TextField(blank=True, verbose_name='范围清单快照')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '备份任务',
                'verbose_name_plural': '备份任务',
                'ordering': ['-created'],
            },
        ),
    ]
