# Generated by Django 5.2 on 2026-09-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='内容')),
                ('source_ref', models.CharField(blank=True, help_text='如 某书/某文/划句来源', max_length=256, verbose_name='来源引用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '灵感',
                'verbose_name_plural': '灵感',
                'ordering': ['-created'],
            },
        ),
    ]
