# Generated by Django 5.2 on 2026-09-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='context',
            field=models.CharField(blank=True, default='', help_text='记录时的背景或补充上下文，可选', max_length=512, verbose_name='上下文'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='source_ref',
            field=models.CharField(blank=True, default='', help_text='如 某书/某文/划句来源', max_length=256, verbose_name='来源'),
        ),
    ]
