# Generated by Django 5.2 on 2026-09-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0002_inspiration_context_alter_inspiration_source_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('insp', '灵感库'), ('gold', '金句库'), ('kb', '知识库')], max_length=8, verbose_name='记入库')),
                ('text', models.TextField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '随笔记历史',
                'verbose_name_plural': '随笔记历史',
                'ordering': ['-created'],
            },
        ),
    ]
